---
driver:
  customize:
    memory: 2048
  name: vagrant
  network:
     - ["forwarded_port", {guest: 8080, host: 8080}]
     - ["forwarded_port", {guest: 8081, host: 8081}]

provisioner:
  name: chef_solo
  require_chef_omnibus: true

platforms:
  - name: ubuntu-14.04

suites:
  - name: jenkins
    run_list:
      - recipe[ark]
      - recipe[git]
      - recipe[java]
      - recipe[mysql::server]
      - recipe[mysql::client]
      - recipe[database::mysql]
      - recipe[nginx]
      - recipe[jtalks-infra::crowd]
      - recipe[jtalks-infra::jenkins]
      - recipe[jtalks-infra::nginx]
  - name: crowd
    run_list:
       - recipe[ark]
       - recipe[java]
       - recipe[mysql::server]
       - recipe[mysql::client]
       - recipe[database::mysql]
       - recipe[nginx]
       - recipe[jtalks-infra::crowd]
       - recipe[jtalks-infra::nginx]
  - name: users
    run_list:
       - recipe[jtalks-infra::users]
       - recipe[sudo]
  - name: cicd
    run_list:
       - recipe[build-essential]
       - recipe[python]
       - recipe[jtalks-infra::cicd]
  - name: server
    run_list:
       - recipe[build-essential]
       - recipe[python]
       - recipe[sudo]
       - recipe[vim]
       - recipe[ark]
       - recipe[git]
       - recipe[java]
       - recipe[mysql::server]
       - recipe[mysql::client]
       - recipe[database::mysql]
       - recipe[nginx]
       - recipe[jtalks-infra::cicd]
       - recipe[jtalks-infra::users]
       - recipe[jtalks-infra::crowd]
       - recipe[jtalks-infra::jenkins]
       - recipe[jtalks-infra::nginx]
