---
driver:
  customize:
    memory: 4096
  name: vagrant
  network:
     - ["forwarded_port", {guest: 8045, host: 8045}]
     - ["forwarded_port", {guest: 8050, host: 8050}]
     - ["forwarded_port", {guest: 8059, host: 8059}]
     - ["forwarded_port", {guest: 8080, host: 8080}]
     - ["forwarded_port", {guest: 8081, host: 8081}]
     - ["forwarded_port", {guest: 8082, host: 8082}]
     - ["forwarded_port", {guest: 8085, host: 8085}]
     - ["forwarded_port", {guest: 9000, host: 9000}]
     - ["forwarded_port", {guest: 8000, host: 8000}]

provisioner:
  name: chef_solo
  require_chef_omnibus: true

platforms:
  - name: ubuntu-14.04

suites:
  - name: jenkins
    run_list:
      - recipe[ark]
      - recipe[git]
      - recipe[git_user]
      - recipe[jtalks-infra::users]
      - recipe[sudo]
      - recipe[java]
      - recipe[database::mysql]
      - recipe[nginx]
      - recipe[jtalks-infra::crowd]
      - recipe[jtalks-infra::jenkins]
  - name: crowd
    run_list:
       - recipe[ark]
       - recipe[java]
       - recipe[jtalks-infra::users]
       - recipe[sudo]
       - recipe[database::mysql]
       - recipe[nginx]
       - recipe[jtalks-infra::crowd]
  - name: users
    run_list:
       - recipe[jtalks-infra::users]
       - recipe[sudo]
  - name: db-users
    run_list:
       - recipe[database::mysql]
       - recipe[jtalks-infra::mysql]
  - name: cicd
    run_list:
       - recipe[build-essential]
       - recipe[python]
       - recipe[jtalks-infra::cicd]
  - name: backup
    run_list:
       - recipe[cron]
       - recipe[jtalks-infra::backup]
  - name: pochta
    run_list:
       - recipe[jtalks-infra::users]
       - recipe[sudo]
       - recipe[jtalks-infra::pochta]
  - name: selenium
    run_list:
       - recipe[jtalks-infra::users]
       - recipe[sudo]
       - recipe[jtalks-infra::selenium]
  - name: sonar
    run_list:
       - recipe[ark]
       - recipe[java]
       - recipe[jtalks-infra::users]
       - recipe[sudo]
       - recipe[database::mysql]
       - recipe[jtalks-infra::mysql]
       - recipe[jtalks-infra::crowd]
       - recipe[jtalks-infra::sonar]
  - name: nexus
    run_list:
       - recipe[ark]
       - recipe[java]
       - recipe[jtalks-infra::users]
       - recipe[sudo]
       - recipe[database::mysql]
       - recipe[jtalks-infra::mysql]
       - recipe[jtalks-infra::crowd]
       - recipe[jtalks-infra::nexus]
  - name: fisheye
    run_list:
       - recipe[ark]
       - recipe[git]
       - recipe[git_user]
       - recipe[java]
       - recipe[jtalks-infra::users]
       - recipe[sudo]
       - recipe[database::mysql]
       - recipe[jtalks-infra::mysql]
       - recipe[jtalks-infra::crowd]
       - recipe[jtalks-infra::fisheye]
  - name: confluence
    run_list:
       - recipe[ark]
       - recipe[git]
       - recipe[git_user]
       - recipe[java]
       - recipe[jtalks-infra::users]
       - recipe[sudo]
       - recipe[database::mysql]
       - recipe[jtalks-infra::mysql]
       - recipe[jtalks-infra::crowd]
       - recipe[jtalks-infra::confluence]
  - name: jira
    run_list:
       - recipe[ark]
       - recipe[git]
       - recipe[git_user]
       - recipe[java]
       - recipe[jtalks-infra::users]
       - recipe[sudo]
       - recipe[database::mysql]
       - recipe[jtalks-infra::mysql]
       - recipe[jtalks-infra::crowd]
       - recipe[jtalks-infra::jira]
  - name: mail
    run_list:
       - recipe[ark]
       - recipe[nginx]
       - recipe[jtalks-infra::users]
       - recipe[sudo]
       - recipe[jtalks-infra::nginx]
       - recipe[database::mysql]
       - recipe[jtalks-infra::mysql]
       - recipe[jtalks-infra::postfix]
  - name: server
    run_list:
       - recipe[sysctl2]
       - recipe[build-essential]
       - recipe[python]
       - recipe[sudo]
       - recipe[cron]
       - recipe[vim]
       - recipe[ark]
       - recipe[git]
       - recipe[git_user]
       - recipe[java]
       - recipe[database::mysql]
       - recipe[nginx]
       - recipe[newrelic-sysmond]
       - recipe[jtalks-infra::logs]
       - recipe[jtalks-infra::mysql]
       - recipe[jtalks-infra::users]
       - recipe[jtalks-infra::selenium]
       - recipe[jtalks-infra::pochta]
       - recipe[jtalks-infra::cicd]
       - recipe[jtalks-infra::crowd]
       - recipe[jtalks-infra::fisheye]
       - recipe[jtalks-infra::nexus]
       - recipe[jtalks-infra::jenkins]
       - recipe[jtalks-infra::sonar]
       - recipe[jtalks-infra::confluence]
       - recipe[jtalks-infra::jira]
       - recipe[jtalks-infra::nginx]
       - recipe[jtalks-infra::postfix]
       - recipe[jtalks-infra::backup]
