---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  require_chef_omnibus: true

platforms:
  - name: ubuntu-14.04
    run-list:
      - recipe[apt]

suites:
  - name: jenkins
    run_list:
      - recipe[ark]
      - recipe[git]
      - recipe[java]
      - recipe[jtalks-infra::jenkins]