---
driver:
  name: vagrant
  network:
#    - ["public_network", {bridge: "eth0"}]
      - ["forwarded_port", {guest: 8080, host: 8080}]
      - ["private_network", {ip: "192.168.33.33"}]

provisioner:
  name: chef_solo
  require_chef_omnibus: true

platforms:
  - name: ubuntu-14.04
    run-list:
      - recipe[apt]

suites:
  - name: jenkins
    run_list:
      - recipe[ark]
      - recipe[git]
      - recipe[java]
      - recipe[jtalks-infra::jenkins]