source 'https://rubygems.org'
gem 'test-kitchen'
gem 'kitchen-vagrant'
gem 'rspec', '3.0.0'
gem 'rspec-core', '3.0.0'
gem 'rspec-expectations', '3.0.0'
gem 'serverspec', '2.0.1'
gem 'berkshelf', '3.2.1'
gem 'ruby-shadow', '2.3.4'
gem 'sequel', '4.18.0'
gem 'addressable', '~> 2.3.6'